# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import mistune


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 694)
        MainWindow.setAutoFillBackground(False)
        self.mainWindowLayout = QtWidgets.QWidget(MainWindow)
        self.mainWindowLayout.setObjectName("mainWindowLayout")
        self.gridLayout = QtWidgets.QGridLayout(self.mainWindowLayout)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.editorTabWidget = QtWidgets.QTabWidget(self.mainWindowLayout)
        self.editorTabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.editorTabWidget.setAutoFillBackground(False)
        self.editorTabWidget.setStyleSheet("")
        self.editorTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.editorTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.editorTabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.editorTabWidget.setUsesScrollButtons(True)
        self.editorTabWidget.setDocumentMode(True)
        self.editorTabWidget.setTabsClosable(True)
        self.editorTabWidget.setMovable(True)
        self.editorTabWidget.setTabBarAutoHide(True)
        self.editorTabWidget.setObjectName("editorTabWidget")

        self.editorTabLayout_1 = QtWidgets.QWidget()
        self.editorTabLayout_1.setEnabled(True)
        self.editorTabLayout_1.setObjectName("editorTabLayout_1")

        self.gridLayout_3 = QtWidgets.QGridLayout(self.editorTabLayout_1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")

        self.textEdit = QtWidgets.QTextEdit(self.editorTabLayout_1)
        self.textEdit.setStyleSheet("")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setLineWidth(1)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 0, 0, 1, 1)
        # https://pypi.org/project/mistune/
        self.markdown = mistune.Markdown()
        self.textEdit.append(self.markdown('# I am using the mistune markdown parser \n\n **Lets see if this works**'))

        self.editorTabWidget.addTab(self.editorTabLayout_1, "")
        self.gridLayout.addWidget(self.editorTabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.mainWindowLayout)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1057, 21))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFormat = QtWidgets.QMenu(self.menuBar)
        self.menuFormat.setObjectName("menuFormat")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.fileExplorerDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.fileExplorerDockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.fileExplorerDockWidget.setObjectName("fileExplorerDockWidget")
        self.fileExplorerDockLayout = QtWidgets.QWidget()
        self.fileExplorerDockLayout.setObjectName("fileExplorerDockLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fileExplorerDockLayout)
        self.gridLayout_2.setContentsMargins(1, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeView = QtWidgets.QTreeView(self.fileExplorerDockLayout)
        self.treeView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)
        self.gridLayout_2.addWidget(self.treeView, 0, 0, 1, 1)
        self.fileExplorerDockWidget.setWidget(self.fileExplorerDockLayout)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.fileExplorerDockWidget)

        self.markupPreviewDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.markupPreviewDockWidget.setStyleSheet("")
        self.markupPreviewDockWidget.setObjectName("markupPreviewDockWidget")
        self.markupPreviewDockLayout = QtWidgets.QWidget()
        self.markupPreviewDockLayout.setObjectName("markupPreviewDockLayout")

        self.gridLayout_4 = QtWidgets.QGridLayout(self.markupPreviewDockLayout)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")

        self.widget = QtWidgets.QWidget(self.markupPreviewDockLayout)
        self.widget.setObjectName("widget")
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        self.markupPreviewDockWidget.setWidget(self.markupPreviewDockLayout)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.markupPreviewDockWidget)

        self.terminalDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.terminalDockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.terminalDockWidget.setObjectName("terminalDockWidget")
        self.terminalDockLayout = QtWidgets.QWidget()
        self.terminalDockLayout.setObjectName("terminalDockLayout")
        self.terminalDockWidget.setWidget(self.terminalDockLayout)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.terminalDockWidget)

        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionTheme = QtWidgets.QAction(MainWindow)
        self.actionTheme.setObjectName("actionTheme")
        self.actionStylesheet = QtWidgets.QAction(MainWindow)
        self.actionStylesheet.setObjectName("actionStylesheet")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addAction(self.actionTheme)
        self.menuSettings.addAction(self.actionStylesheet)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuFormat.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.editorTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.editorTabWidget.setTabText(self.editorTabWidget.indexOf(self.editorTabLayout_1), _translate("MainWindow", "Tab 1"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuFormat.setTitle(_translate("MainWindow", "Format"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.fileExplorerDockWidget.setWindowTitle(_translate("MainWindow", "File explorer"))
        self.markupPreviewDockWidget.setWindowTitle(_translate("MainWindow", "Markdown preview"))
        self.terminalDockWidget.setWindowTitle(_translate("MainWindow", "Terminal"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionTheme.setText(_translate("MainWindow", "Theme"))
        self.actionStylesheet.setText(_translate("MainWindow", "Stylesheet"))
