from PyQt5 import QtCore, QtWidgets

from src import config
from src.widgets import MarkupEditor


class MainWindowUI(object):
    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(config.UI_RESOLUTION[0], config.UI_RESOLUTION[1])
        main_window.setAutoFillBackground(False)

        self.mainWindowLayout = QtWidgets.QWidget(main_window)
        self.mainWindowLayout.setObjectName("mainWindowLayout")
        main_window.setCentralWidget(self.mainWindowLayout)

        self.menuBar = QtWidgets.QMenuBar(main_window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1057, 21))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFormat = QtWidgets.QMenu(self.menuBar)
        self.menuFormat.setObjectName("menuFormat")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        main_window.setMenuBar(self.menuBar)
        self.fileExplorerDockWidget = QtWidgets.QDockWidget(main_window)
        self.fileExplorerDockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.fileExplorerDockWidget.setObjectName("fileExplorerDockWidget")
        self.fileExplorerDockLayout = QtWidgets.QWidget()
        self.fileExplorerDockLayout.setObjectName("fileExplorerDockLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fileExplorerDockLayout)
        self.gridLayout_2.setContentsMargins(1, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeView = QtWidgets.QTreeView(self.fileExplorerDockLayout)
        self.treeView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)
        self.gridLayout_2.addWidget(self.treeView, 0, 0, 1, 1)
        self.fileExplorerDockWidget.setWidget(self.fileExplorerDockLayout)
        main_window.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.fileExplorerDockWidget)

        self.markupEditorWidget = MarkupEditor.MarkupEditorUI()
        self.markupEditorWidget.setup_ui(main_window)

        self.markupPreviewDockWidget = QtWidgets.QDockWidget(main_window)
        self.markupPreviewDockWidget.setStyleSheet("")
        self.markupPreviewDockWidget.setObjectName("markupPreviewDockWidget")
        self.markupPreviewDockLayout = QtWidgets.QWidget()
        self.markupPreviewDockLayout.setObjectName("markupPreviewDockLayout")

        self.gridLayout_4 = QtWidgets.QGridLayout(self.markupPreviewDockLayout)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")

        self.widget = QtWidgets.QWidget(self.markupPreviewDockLayout)
        self.widget.setObjectName("widget")
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        self.markupPreviewDockWidget.setWidget(self.markupPreviewDockLayout)
        main_window.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.markupPreviewDockWidget)

        self.terminalDockWidget = QtWidgets.QDockWidget(main_window)
        self.terminalDockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.terminalDockWidget.setObjectName("terminalDockWidget")
        self.terminalDockLayout = QtWidgets.QWidget()
        self.terminalDockLayout.setObjectName("terminalDockLayout")
        self.terminalDockWidget.setWidget(self.terminalDockLayout)
        main_window.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.terminalDockWidget)

        self.actionSave = QtWidgets.QAction(main_window)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(main_window)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPreferences = QtWidgets.QAction(main_window)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionTheme = QtWidgets.QAction(main_window)
        self.actionTheme.setObjectName("actionTheme")
        self.actionStylesheet = QtWidgets.QAction(main_window)
        self.actionStylesheet.setObjectName("actionStylesheet")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addAction(self.actionTheme)
        self.menuSettings.addAction(self.actionStylesheet)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuFormat.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuFormat.setTitle(_translate("MainWindow", "Format"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.fileExplorerDockWidget.setWindowTitle(_translate("MainWindow", "File explorer"))
        self.markupPreviewDockWidget.setWindowTitle(_translate("MainWindow", "Markdown preview"))
        self.terminalDockWidget.setWindowTitle(_translate("MainWindow", "Terminal"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionTheme.setText(_translate("MainWindow", "Theme"))
        self.actionStylesheet.setText(_translate("MainWindow", "Stylesheet"))

        self.markupEditorWidget.retranslate_ui(main_window)
